language: node_js
node_js:
- '8'
matrix:
  fast_finish: true
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version
script:
- yarn lint
- yarn test